export enum NotificationType {
    SYSTEM = 'SYSTEM',

    USER_INVITED = 'USER_INVITED',

    PASSWORD_RESET = 'PASSWORD_RESET',

    PURCHASE_ORDER_CREATED = 'PURCHASE_ORDER_CREATED',

    PURCHASE_ORDER_APPROVED = 'PURCHASE_ORDER_APPROVED',

    RFQ_CREATED = 'RFQ_CREATED',

    CONTRACT_EXPIRING = 'CONTRACT_EXPIRING',
}