export enum EventTypes {
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',

    ROLE_ASSIGNED = 'ROLE_ASSIGNED',
    ROLE_REMOVED = 'ROLE_REMOVED',

    PERMISSION_ASSIGNED = 'PERMISSION_ASSIGNED',
    PERMISSION_REMOVED = 'PERMISSION_REMOVED',

    USER_LOGIN = 'USER_LOGIN',
    USER_LOGOUT = 'USER_LOGOUT',

    TENANT_CREATED = 'TENANT_CREATED',
    TENANT_UPDATED = 'TENANT_UPDATED',
}